---
# tasks file for sshd
# No need to ensure that openssh-server is installed, as ansible is already using it 

- name: Ensuring sshd is enabled
  service:
    name: sshd
    enabled: True

- name: Distributing sshd config files 
  template:
    src: "{{ item }}.j2"
    dest: "/etc/ssh/{{ item }}"
    mode: 0644 
  with_items:
    - sshd_config
    - ssh_known_hosts
  notify: 
    - restart_sshd

- name: Local script for ssh facts.d
  copy:
    src: sshd-fingerprints
    dest: /usr/local/bin/sshd-fingerprints
    mode: 0750
  register: sshd_host_facts  

- name: Creating facts.d
  command: /usr/local/bin/sshd-fingerprints
  when: sshd_host_facts is changed 

- name: Reloading facts if needed
  setup:
    filter: ansible_local
  when: sshd_host_facts is changed 

- block:
    - name: Adding group "{{ sshd_proxyjump_group }}"
      group:
        name: "{{ sshd_proxyjump_group }}"
      tags:
        - users

    - name: Adding ssh proxyjump users
      user:
        name: "{{ item.login_name }}"
        state: present
        comment: "{{ item.full_name }}"
        shell: /bin/false
        append: yes
        groups: "{{ sshd_proxyjump_group }}"
      with_items: "{{ sshd_proxyjump_users_list }}"
      loop_control:
        label: "{{ item.login_name }}"
      tags:
        - users

    - name: Importing ssh proxyjump users pub keys
      authorized_key:
        user: "{{ item.0.login_name }}"
        key: "{{ item.1 }}"
      with_subelements:
        - "{{ sshd_proxyjump_users_list }}"
        - ssh_pub_keys
      loop_control:
        label: "{{ item.0.login_name }}"
      tags:
        - users
  when: sshd_proxyjump_host

- block:
    - name: Ensuring we have directory to store sshd host keys to be signed
      file:
        path: /var/lib/centos-infra/pki-ssh
        state: directory
        owner: root
        group: root
        mode: '0750'

    - name: Distributing existing openssh CA key files
      copy:
        src: "{{ pkistore }}/ssh/{{ item }}"
        dest: "/var/lib/centos-infra/pki-ssh/{{ item }}"
        owner: root
        group: root
      with_items:
        - "{{ sshd_ca_host_key }}"
        - "{{ sshd_ca_host_key }}.pub"

  when: sshd_ca_host
