---
# tasks file for sshd
# No need to ensure that openssh-server is installed, as ansible is already using it 

- name: Ensuring sshd is enabled
  service:
    name: sshd
    enabled: True

- name: Distributing sshd config files 
  template:
    src: "{{ item }}.j2"
    dest: "/etc/ssh/{{ item }}"
  with_items:
    - sshd_config
    - ssh_known_hosts
  notify: 
    - restart_sshd

- name: Local script for ssh facts.d
  copy:
    src: sshd-fingerprints
    dest: /usr/local/bin/sshd-fingerprints
    mode: 0750
  register: sshd_host_facts  

- name: Creating facts.d
  command: /usr/local/bin/sshd-fingerprints
  when: sshd_host_facts is changed 

- name: Reloading facts if needed
  setup:
    filter: ansible_local
  when: sshd_host_facts is changed  
